In [1]:
import numpy as np

In [2]:
a = np.arange(0, 10)
print(a)
b = np.arange(10, 20)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [3]:
np.hstack((a, b)).shape

(20,)

In [4]:
np.vstack((a,b)).shape

(2, 10)

In [5]:
c = a.reshape(2,5)
d= b.reshape(2,5)

In [6]:
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
d

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [8]:
np.hstack((c,d))

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [9]:
np.vstack((c,d))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [10]:
np.c_[a,b]

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19]])

In [11]:
np.r_[a,b]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
np.r_[c, d]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [13]:
np.shape(np.c_[a,b])

(10, 2)

In [14]:
np.shape(np.r_[c,d])

(4, 5)