In [3]:
 import numpy as np

In [4]:
np.__version__

'1.14.3'

In [5]:
 a = np.arange(15).reshape(3, 5)
 a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
 a.shape

(3, 5)

In [7]:
a.ndim

2

In [8]:
a.dtype.name

'int32'

In [9]:
 a.itemsize

4

In [10]:
 a.size

15

In [11]:
type(a)

numpy.ndarray

In [12]:
a = np.array([2,3,4])
a.dtype

dtype('int32')

In [13]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [14]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [19]:
#print(np.zeros( (3,4) ))
#print(np.ones( (3,4) ))
#print(np.empty( (3,4) ))
print(np.repeat(1, 10).reshape(2, 5))

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [25]:
test = np.arange(8).reshape(4, 2)
print(np.zeros_like(test))
print(np.ones_like(test))
print(np.empty_like(test))

[[0 0]
 [0 0]
 [0 0]
 [0 0]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [26]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [27]:
np.arange( 0, 2, 0.3 )

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [30]:
np.linspace(0,100,100)

array([  0.        ,   1.01010101,   2.02020202,   3.03030303,
         4.04040404,   5.05050505,   6.06060606,   7.07070707,
         8.08080808,   9.09090909,  10.1010101 ,  11.11111111,
        12.12121212,  13.13131313,  14.14141414,  15.15151515,
        16.16161616,  17.17171717,  18.18181818,  19.19191919,
        20.2020202 ,  21.21212121,  22.22222222,  23.23232323,
        24.24242424,  25.25252525,  26.26262626,  27.27272727,
        28.28282828,  29.29292929,  30.3030303 ,  31.31313131,
        32.32323232,  33.33333333,  34.34343434,  35.35353535,
        36.36363636,  37.37373737,  38.38383838,  39.39393939,
        40.4040404 ,  41.41414141,  42.42424242,  43.43434343,
        44.44444444,  45.45454545,  46.46464646,  47.47474747,
        48.48484848,  49.49494949,  50.50505051,  51.51515152,
        52.52525253,  53.53535354,  54.54545455,  55.55555556,
        56.56565657,  57.57575758,  58.58585859,  59.5959596 ,
        60.60606061,  61.61616162,  62.62626263,  63.63

In [31]:
 np.random.rand(3,2)

array([[0.54443619, 0.98483716],
       [0.71451979, 0.78586721],
       [0.94935991, 0.22211209]])

In [32]:
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [33]:
n = np.arange(10000).reshape(100, 100)
n

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [37]:
#np.set_printoptions(threshold=np.nan)
#n

In [44]:
a = np.array([1, 4, 50, 2])
b = np.array([20, 34, 54, 21])
print(a+b)
print(a**2)
print(a-b)
print(a*b)
print(a@b)

[ 21  38 104  23]
[   1   16 2500    4]
[-19 -30  -4 -19]
[  20  136 2700   42]
2898


In [43]:
a = np.array([[1, 0], [2, 1]])
b = np.array([[1, 1], [2, 0]])
print(a@b)
print(a.dot(b))
print(a*b)

[[1 1]
 [4 2]]
[[1 1]
 [4 2]]
[[1 0]
 [4 0]]


In [45]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,np.pi,3)
c = a+b
c

array([1.        , 2.57079633, 4.14159265])

In [49]:
a = np.random.random((2,3))
print(a)
print(a.sum())
print(a.min())
print(a.max())

[[0.84440591 0.07478712 0.83138546]
 [0.11345518 0.04309939 0.42388979]]
2.331022851476014
0.04309939297481391
0.8444059149100922


## arithmetic operations

In [53]:
b = np.arange(12).reshape(3,4)
print(b)
b.sum(axis = 0)#sum column
b.sum(axis = 1)#sum row
b.cumsum(axis=1)#cumulative sum row

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [54]:
B = np.arange(3)
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [55]:
print(np.sqrt(B))
C = np.array([12, 4, 5])
print(np.add(B, C))

[0.         1.         1.41421356]
[12  5  7]


In [56]:
x = np.arange(4).reshape((2,2))
print(x)
np.transpose(x)

[[0 1]
 [2 3]]


array([[0, 2],
       [1, 3]])

In [57]:
goodvalues = [3, 4, 7]
ix = np.isin(x, goodvalues)
ix
np.where(ix)


(array([1], dtype=int64), array([1], dtype=int64))

In [58]:
a = np.array([[1, 2, 4], [3, 4, 6]])
print(np.mean(a))
print(np.median(a))
print(np.std(a[:, 0]))
print(np.corrcoef(a[:, 0], a[:, 1]))


3.3333333333333335
3.5
1.0
[[1. 1.]
 [1. 1.]]


In [59]:
x = [-2.1, -1,  4.3]
y = [3,  1.1,  0.12]
print(np.cov(x, y))

[[11.71       -4.286     ]
 [-4.286       2.14413333]]


## slicing

In [60]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [61]:
print(a[2])

8


In [62]:
print(a[:])

[  0   1   8  27  64 125 216 343 512 729]


In [63]:
print(a[3:])

[ 27  64 125 216 343 512 729]


In [64]:
print(a[3:7])

[ 27  64 125 216]


In [65]:
print(a[-1])

729


In [66]:
print(a[ :4])

[ 0  1  8 27]


In [67]:
a[:6:2] = -1000 
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [68]:
a = np.random.random((3, 5))
a

array([[0.18429121, 0.51222094, 0.90546442, 0.7151704 , 0.96062343],
       [0.81070724, 0.23981484, 0.37423447, 0.35356269, 0.78306562],
       [0.27715108, 0.52268605, 0.81226797, 0.39423808, 0.64289881]])

In [69]:
a[2, 3]

0.3942380839878057

In [70]:
a[:, 3]

array([0.7151704 , 0.35356269, 0.39423808])

In [71]:
a[0, :]

array([0.18429121, 0.51222094, 0.90546442, 0.7151704 , 0.96062343])

In [72]:
a[0:2, 4]

array([0.96062343, 0.78306562])

In [73]:
for element in b.flat:
       print(element)

0
1
2
3
4
5
6
7
8
9
10
11


In [74]:
bmi=np.array([20,21,22,23,24,25])
print(bmi[1])
print(bmi>23)
print(bmi[bmi>23])
print(type(bmi))
print(bmi.max())  #similarly min()

21
[False False False False  True  True]
[24 25]
<class 'numpy.ndarray'>
25


In [75]:
a=np.arange(10).reshape(2,-1)
b=np.arange(10).reshape(2,-1)
#method 1
np.concatenate([a,b],axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Generating some patterns

In [76]:
a=np.array([1,2,3])
#repeat one one element of an array n times
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [77]:
#repeat full array n times
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [78]:
#common items between two arrays
a=np.arange(10)
b=np.arange(0,10,2)
np.intersect1d(a,b)

array([0, 2, 4, 6, 8])

In [79]:
#remove redundant elements
print(a)
print(b)
np.setdiff1d(a,b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


array([1, 3, 5, 7, 9])

In [80]:
#extracting elements within given range
a=np.arange(15)
#m1
index=np.where((a>=5)&(a<=10))
a[index]

array([ 5,  6,  7,  8,  9, 10])

In [81]:
#another method m2
index=np.where(np.logical_and(a>=5,a<=10))
a[index]

array([ 5,  6,  7,  8,  9, 10])